"""Render FUNNEL.md — the measured answer to "how many reliable tasks does
one packaged repo yield with no human expert?" — from disk facts only.

    python3 funnel_report.py --verdicts .work/funnel*/verdicts.jsonl [...]
"""

import argparse
import collections
import json
import os
import statistics
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import config  # noqa: E402
import lib  # noqa: E402

STAGES = ["survivor", "floor_high", "silent", "marginal", "apply_fail",
          "build_fail", "roundtrip_fail", "worker_error"]


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--verdicts", nargs="+", required=True)
    ap.add_argument("--out", default=os.path.join(
        os.path.dirname(os.path.abspath(__file__)), "FUNNEL.md"))
    args = ap.parse_args()

    rows = []
    for p in args.verdicts:
        rows.extend(lib.read_jsonl(p))
    bank_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "BANK.json")
    bank = json.load(open(bank_path)) if os.path.isfile(bank_path) else []
    packaged_ids = {b["id"] for b in bank}

    def table(keyfn, title):
        counts = collections.defaultdict(lambda: collections.defaultdict(int))
        for r in rows:
            counts[keyfn(r)][r["status"]] += 1
        used = [s for s in STAGES if any(c.get(s) for c in counts.values())]
        out = [f"### {title}", "", "| " + title.split()[0].lower() + " | total | " +
               " | ".join(used) + " | packaged |",
               "|" + "---|" * (len(used) + 3)]
        for key in sorted(counts):
            c = counts[key]
            total = sum(c.values())
            pk = sum(1 for r in rows if keyfn(r) == key and r["id"] in packaged_ids)
            out.append(f"| {key} | {total} | " +
                       " | ".join(str(c.get(s, 0)) for s in used) + f" | {pk} |")
        return "\n".join(out) + "\n"

    surv = [r for r in rows if r["status"] == "survivor"]
    floors = [r["floor"] for r in surv]
    lines = [
        "# Funnel numbers — one repo, no experts",
        "",
        "Generated by funnel_report.py from verdicts.jsonl; regenerate, never",
        "hand-edit. Thresholds: FLOOR_MAX "
        f"{config.FLOOR_MAX}, MARGIN_MIN {config.MARGIN_MIN}.",
        "",
        f"**{len(rows)} candidates screened -> {len(surv)} survivors -> "
        f"{len(bank)} packaged tasks** (diversity dedup: "
        f"{config.DEDUP_PER_GROUP} per (tree, file, family); every survivor "
        "is packageable with --all).",
        "",
        f"Survivor floors: min {min(floors):.2f} / mean "
        f"{statistics.mean(floors):.2f} / max {max(floors):.2f}. "
        "Floors are native estimates; each verifier re-measures its own in situ.",
        "",
        table(lambda r: r["source"], "source (how the defect was made)"),
        table(lambda r: r["family"], "family (what kind of defect)"),
        table(lambda r: r["tree"], "tree (which solver)"),
        "### What died, and why that is the product",
        "",
        "- **silent** — no observable symptom on these decks (zero-field",
        "  couplings, dealiased modes, dead branches): every one a broken",
        "  task if packaged blind. The funnel is the answer-entropy check",
        "  of TAXONOMY.md run behaviorally.",
        "- **marginal** — divergence within noise of the 1e-10 bound.",
        "- **floor_high** — the unfixed build already scores > "
        f"{config.FLOOR_MAX} (no headroom for the raw reward; still",
        "  listed in verdicts for curriculum use with reward_repair).",
        "",
        "Wall cost of the screen: see each run's report.json; the first",
        "mass run screened 233 candidates in 305 s on 16 slots (this box).",
    ]
    with open(args.out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote", args.out)


if __name__ == "__main__":
    main()
